### PR TITLE
all icons

### PR DESCRIPTION
**Pull request by hrissolo**

### CODE REVIEW

**Comment by AudreyThomasson** [comment]
Should these be in the public images folder instead?

**Review by richieholsenback — APPROVED** [review]
Looks great!

**Review by HanakoH — COMMENTED** [review]
Ooh I just noticed we don't have VS Code. Could we also get that one in?

**Review by richieholsenback — APPROVED** [review]
👍

**Review by HanakoH — APPROVED** [review]
ℬoom

**Comment by HanakoH** [comment]
Thank youu!
^-^

**Pull request merged**
